### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by aiboyko** [YueJiang-nj/CVPR2020-SDFDiff#2]
Hi! Very interesing paper!
But I can't reproduce the code.
It does not compile. (Ubuntu 20, CUDA 10.2, pytorch=1.5, python=3.7)

Could you please outline the exact prerequisites like in 
https://github.com/B1ueber2y/DIST-Renderer

Just in case, maybe you could see what's wrong here, here is output of compilation:

`
running install
running bdist_egg
running egg_info
writing renderer.egg-info/PKG-INFO
writing dependency_links to renderer.egg-info/dependency_links.txt
writing top-level names to renderer.egg-info/top_level.txt
reading manifest file 'renderer.egg-info/SOURCES.txt'
writing manifest file 'renderer.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'renderer' extension
Emitting ninja build file /home/ab/Documents/CVPR2020-SDFDiff/single_view_code/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] /usr/bin/nvcc -I/home/ab/anaconda3/lib/python3.7/site-packages/torch/include -I/home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/ab/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/home/ab/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/home/ab/anaconda3/include/python3.7m -c -c /home/ab/Documents/CVPR2020-SDFDiff/single_view_code/renderer_kernel.cu -o /home/ab/Documents/CVPR2020-SDFDiff/single_view_code/build/temp.linux-x86_64-3.7/renderer_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=renderer -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
FAILED: /home/ab/Documents/CVPR2020-SDFDiff/single_view_code/build/temp.linux-x86_64-3.7/renderer_kernel.o 
/usr/bin/nvcc -I/home/ab/anaconda3/lib/python3.7/site-packages/torch/include -I/home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/ab/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/home/ab/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/home/ab/anaconda3/include/python3.7m -c -c /home/ab/Documents/CVPR2020-SDFDiff/single_view_code/renderer_kernel.cu -o /home/ab/Documents/CVPR2020-SDFDiff/single_view_code/build/temp.linux-x86_64-3.7/renderer_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=renderer -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
/usr/include/c++/8/utility(307): error: pack expansion does not make use of any argument packs

/usr/include/c++/8/utility(329): error: pack expansion does not make use of any argument packs

/usr/include/c++/8/utility(329): error: expected a ">"
          detected during instantiation of type "std::make_integer_sequence<std::size_t, _Num>" 
(340): here

/usr/include/c++/8/utility(329): error: identifier "__integer_pack" is undefined
          detected during:
            instantiation of type "std::make_integer_sequence<std::size_t, 0UL>" 
(340): here
            instantiation of type "std::make_index_sequence<0UL>" 
/home/ab/anaconda3/lib/python3.7/site-packages/torch/include/ATen/core/op_registration/infer_schema.h(81): here
            instantiation of "std::array<c10::detail::infer_schema::ArgumentDef, <expression>> c10::detail::infer_schema::createReturns<std::tuple<ReturnTypes...>, void>::call() [with ReturnTypes=<>]" 
/home/ab/anaconda3/lib/python3.7/site-packages/torch/include/ATen/core/op_registration/infer_schema.h(96): here

/home/ab/anaconda3/lib/python3.7/site-packages/torch/include/ATen/core/op_registration/infer_schema.h(80): error: no instance of function template "c10::detail::infer_schema::createArgumentVectorFromTypes" matches the argument list
            argument types are: (<error-type>)
          detected during instantiation of "std::array<c10::detail::infer_schema::ArgumentDef, <expression>> c10::detail::infer_schema::createReturns<std::tuple<ReturnTypes...>, void>::call() [with ReturnTypes=<>]" 
(96): here

5 errors detected in the compilation of "/tmp/tmpxft_00008345_00000000-6_renderer_kernel.cpp1.ii".
[2/2] c++ -MMD -MF /home/ab/Documents/CVPR2020-SDFDiff/single_view_code/build/temp.linux-x86_64-3.7/renderer.o.d -pthread -B /home/ab/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ab/anaconda3/lib/python3.7/site-packages/torch/include -I/home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/ab/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/home/ab/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/home/ab/anaconda3/include/python3.7m -c -c /home/ab/Documents/CVPR2020-SDFDiff/single_view_code/renderer.cpp -o /home/ab/Documents/CVPR2020-SDFDiff/single_view_code/build/temp.linux-x86_64-3.7/renderer.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=renderer -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/c10/core/Device.h:5:0,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/c10/core/Allocator.h:6,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/ATen/ATen.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from /home/ab/Documents/CVPR2020-SDFDiff/single_view_code/renderer.cpp:1:
/home/ab/Documents/CVPR2020-SDFDiff/single_view_code/renderer.cpp: In function ‘std::vector<at::Tensor> ray_matching(at::Tensor, at::Tensor, at::Tensor, int, int, float, float, float, float, float, float, int, int, int, float, float, float)’:
/home/ab/Documents/CVPR2020-SDFDiff/single_view_code/renderer.cpp:23:41: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
 #define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be a CUDA tensor")
                                         ^
/home/ab/anaconda3/lib/python3.7/site-packages/torch/include/c10/util/Exception.h:164:39: note: in definition of macro ‘C10_EXPAND_MSVC_WORKAROUND’
 #define C10_EXPAND_MSVC_WORKAROUND(x) x
                                       ^
/home/ab/anaconda3/lib/python3.7/site-packages/torch/include/c10/util/Exception.h:183:34: note: in expansion of macro ‘C10_UNLIKELY’
 #define C10_UNLIKELY_OR_CONST(e) C10_UNLIKELY(e)
                                  ^~~~~~~~~~~~
/home/ab/anaconda3/lib/python3.7/site-packages/torch/include/c10/util/Exception.h:220:7: note: in expansion of macro ‘C10_UNLIKELY_OR_CONST’
   if (C10_UNLIKELY_OR_CONST(!(cond))) {       \
       ^~~~~~~~~~~~~~~~~~~~~
/home/ab/anaconda3/lib/python3.7/site-packages/torch/include/c10/util/Exception.h:410:32: note: in expansion of macro ‘TORCH_INTERNAL_ASSERT’
     C10_EXPAND_MSVC_WORKAROUND(TORCH_INTERNAL_ASSERT(cond, __VA_ARGS__));     \
                                ^~~~~~~~~~~~~~~~~~~~~
/home/ab/Documents/CVPR2020-SDFDiff/single_view_code/renderer.cpp:23:23: note: in expansion of macro ‘AT_ASSERTM’
 #define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be a CUDA tensor")
                       ^~~~~~~~~~
/home/ab/Documents/CVPR2020-SDFDiff/single_view_code/renderer.cpp:25:24: note: in expansion of macro ‘CHECK_CUDA’
 #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
                        ^~~~~~~~~~
/home/ab/Documents/CVPR2020-SDFDiff/single_view_code/renderer.cpp:45:5: note: in expansion of macro ‘CHECK_INPUT’
     CHECK_INPUT(w_h_3);
     ^
In file included from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:11:0,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Context.h:4,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from /home/ab/Documents/CVPR2020-SDFDiff/single_view_code/renderer.cpp:1:
/home/ab/anaconda3/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:262:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
In file included from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/c10/core/Device.h:5:0,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/c10/core/Allocator.h:6,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/ATen/ATen.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from /home/ab/Documents/CVPR2020-SDFDiff/single_view_code/renderer.cpp:1:
/home/ab/Documents/CVPR2020-SDFDiff/single_view_code/renderer.cpp:23:41: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
 #define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be a CUDA tensor")
                                         ^
/home/ab/anaconda3/lib/python3.7/site-packages/torch/include/c10/util/Exception.h:164:39: note: in definition of macro ‘C10_EXPAND_MSVC_WORKAROUND’
 #define C10_EXPAND_MSVC_WORKAROUND(x) x
                                       ^
/home/ab/anaconda3/lib/python3.7/site-packages/torch/include/c10/util/Exception.h:183:34: note: in expansion of macro ‘C10_UNLIKELY’
 #define C10_UNLIKELY_OR_CONST(e) C10_UNLIKELY(e)
                                  ^~~~~~~~~~~~
/home/ab/anaconda3/lib/python3.7/site-packages/torch/include/c10/util/Exception.h:220:7: note: in expansion of macro ‘C10_UNLIKELY_OR_CONST’
   if (C10_UNLIKELY_OR_CONST(!(cond))) {       \
       ^~~~~~~~~~~~~~~~~~~~~
/home/ab/anaconda3/lib/python3.7/site-packages/torch/include/c10/util/Exception.h:410:32: note: in expansion of macro ‘TORCH_INTERNAL_ASSERT’
     C10_EXPAND_MSVC_WORKAROUND(TORCH_INTERNAL_ASSERT(cond, __VA_ARGS__));     \
                                ^~~~~~~~~~~~~~~~~~~~~
/home/ab/Documents/CVPR2020-SDFDiff/single_view_code/renderer.cpp:23:23: note: in expansion of macro ‘AT_ASSERTM’
 #define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be a CUDA tensor")
                       ^~~~~~~~~~
/home/ab/Documents/CVPR2020-SDFDiff/single_view_code/renderer.cpp:25:24: note: in expansion of macro ‘CHECK_CUDA’
 #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
                        ^~~~~~~~~~
/home/ab/Documents/CVPR2020-SDFDiff/single_view_code/renderer.cpp:46:5: note: in expansion of macro ‘CHECK_INPUT’
     CHECK_INPUT(w_h);
     ^
In file included from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:11:0,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Context.h:4,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from /home/ab/Documents/CVPR2020-SDFDiff/single_view_code/renderer.cpp:1:
/home/ab/anaconda3/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:262:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
In file included from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/c10/core/Device.h:5:0,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/c10/core/Allocator.h:6,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/ATen/ATen.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from /home/ab/Documents/CVPR2020-SDFDiff/single_view_code/renderer.cpp:1:
/home/ab/Documents/CVPR2020-SDFDiff/single_view_code/renderer.cpp:23:41: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
 #define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be a CUDA tensor")
                                         ^
/home/ab/anaconda3/lib/python3.7/site-packages/torch/include/c10/util/Exception.h:164:39: note: in definition of macro ‘C10_EXPAND_MSVC_WORKAROUND’
 #define C10_EXPAND_MSVC_WORKAROUND(x) x
                                       ^
/home/ab/anaconda3/lib/python3.7/site-packages/torch/include/c10/util/Exception.h:183:34: note: in expansion of macro ‘C10_UNLIKELY’
 #define C10_UNLIKELY_OR_CONST(e) C10_UNLIKELY(e)
                                  ^~~~~~~~~~~~
/home/ab/anaconda3/lib/python3.7/site-packages/torch/include/c10/util/Exception.h:220:7: note: in expansion of macro ‘C10_UNLIKELY_OR_CONST’
   if (C10_UNLIKELY_OR_CONST(!(cond))) {       \
       ^~~~~~~~~~~~~~~~~~~~~
/home/ab/anaconda3/lib/python3.7/site-packages/torch/include/c10/util/Exception.h:410:32: note: in expansion of macro ‘TORCH_INTERNAL_ASSERT’
     C10_EXPAND_MSVC_WORKAROUND(TORCH_INTERNAL_ASSERT(cond, __VA_ARGS__));     \
                                ^~~~~~~~~~~~~~~~~~~~~
/home/ab/Documents/CVPR2020-SDFDiff/single_view_code/renderer.cpp:23:23: note: in expansion of macro ‘AT_ASSERTM’
 #define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be a CUDA tensor")
                       ^~~~~~~~~~
/home/ab/Documents/CVPR2020-SDFDiff/single_view_code/renderer.cpp:25:24: note: in expansion of macro ‘CHECK_CUDA’
 #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
                        ^~~~~~~~~~
/home/ab/Documents/CVPR2020-SDFDiff/single_view_code/renderer.cpp:47:5: note: in expansion of macro ‘CHECK_INPUT’
     CHECK_INPUT(grid);
     ^
In file included from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:11:0,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Context.h:4,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/ab/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from /home/ab/Documents/CVPR2020-SDFDiff/single_view_code/renderer.cpp:1:
/home/ab/anaconda3/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:262:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/ab/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1400, in _run_ninja_build
    check=True)
  File "/home/ab/anaconda3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    'build_ext': BuildExtension
  File "/home/ab/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/home/ab/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/ab/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/ab/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/ab/anaconda3/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/ab/anaconda3/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/ab/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/ab/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/ab/anaconda3/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/ab/anaconda3/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/home/ab/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/ab/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/ab/anaconda3/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/ab/anaconda3/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/ab/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/ab/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/ab/anaconda3/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/home/ab/anaconda3/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/ab/anaconda3/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/ab/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "/home/ab/anaconda3/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/ab/anaconda3/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/ab/anaconda3/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/ab/anaconda3/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/ab/anaconda3/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/ab/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 423, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/ab/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/ab/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
`

**Comment by YueJiang-nj** [comment]
Thank you for pointing it out!!
I just uploaded two scripts to create proper virtual environments. (See README)
Let me know whether it helps!
