### ISSUE TITLE
About 'main.py' in the 'single_view_code' directory

### ISSUE THREAD

**Issue by Txusheng** [YueJiang-nj/CVPR2020-SDFDiff#3]
Hi,
Thank you for releasing the codes for your great job in the differentiable SDF rendering.

Currently, I am testing the codes following the instructions. I am confused with some issues as:
1. At line. 8 in the 'main.py' in the 'single_view_code' directory, the code indicates to import the 'dataset' module, but there is no correspoinding file named 'dataset' in the project. 
2. At line. 7 in the 'main.py' in the 'single_view_code' directory, the code tries to import 'Encoder' and 'Decoder' from 'models.py'. However, the corresponding classes are missing in 'models.py'. Instead, I found the classes 'DecoderSimple' and 'EncoderSimple'. Do  'Encoder' and 'Decoder' mean 'DecoderSimple' and 'EncoderSimple'?

**Comment by YueJiang-nj** [comment]
Yes! 'Encoder' and 'Decoder' mean 'DecoderSimple' and 'EncoderSimple'.. Sorry for this confusion. 
I am switching universities, so kind of losing access to my dataset and saved models.. I am trying to get my dataset back..

**Comment by Txusheng** [comment]
> Yes! 'Encoder' and 'Decoder' mean 'DecoderSimple' and 'EncoderSimple'.. Sorry for this confusion.
> I am switching universities, so kind of losing access to my dataset and saved models.. I am trying to get my dataset back..

Thank you very much for your gentle reply!
