### ISSUE TITLE
Questions regarding your paper

### ISSUE THREAD

**Issue by stalkerrush** [YueJiang-nj/CVPR2020-SDFDiff#4]
Hi @YueJiang-nj , congratulation on your great work! I was reading your paper and there are two questions I didn't understand well. It would be great if you can let me know a bit more details about them:

1. As you mentioned in the paper, the selection of the 8 grid points is based on ray intersection point. So if there is no intersection, no gradient will be backpropagated. Then at the beginning, I'm assuming there will be cases where the groundtruth shape does not intersect with the initial shape. In such a case, how can you prevent the model from failing to learn?

2. It seems that you are using Lambertian shading to get the final image from SDF. For single-image shape reconstruction, do you also directly use groundtruth lighting as input? And textures are not considered in this paper right?

Thank you!

**Comment by YueJiang-nj** [comment]
Thanks for your interest and questions!
1. I always put ground truth shape at the center of the bounding box, so the center of ground truth shape is always the same as the center of the initial shape. In this case, they would always overlap.
2. Yes! I use ground truth lighting as input. So the lighting condition is known. And yes, textures are not considered in this paper. But should not be hard to add textures as we know the normals.
